services:
  postgres:
    container_name: postgres
    image: postgres:latest
    volumes:
      - ./database/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=admin
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
  server:
    container_name: server
    build:
      context: ./server
      dockerfile: dockerfile.dev
    ports:
      - "8000:8000"
    volumes:
      - /app/node_modules
      - ./server:/app
    environment:
      - JWTSECRET=PcT5stL9mSfIJ5q02id03UNw6mqEjvdK
      - JWTREFRESHSECRET=WUcpwYiFmPdODhYer07CIQEVF0QsvIEQ
      - JWTEXPIRATION=500000
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=admin
      - PGPORT=5432
      - REDIS_HOST=redis
      - REDIS_PORT=6379
  react-app:
    container_name: react-app
    build:
      context: ./react-app
      dockerfile: dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - ./react-app:/app
  redis:
    container_name: redis
    image: redis:latest


  
